## Source

This variables are created using the transports demand CSVs created in `PASSENGER_TRANSPORT_DEMAND.ipynb`

In [1]:
import numpy as np
import pandas as pd
import os
from utils.utils import EDAUtils, TransportUtils

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
edau = EDAUtils()
tu = TransportUtils()

In [4]:
# Set up paths
CURRENT_DIR_PATH = os.getcwd()
OUTPUT_DATA_DIR_PATH = os.path.join(CURRENT_DIR_PATH, "output_data")
INPUT_DATA_DIR_PATH = os.path.join(CURRENT_DIR_PATH, "input_data")

In [5]:
# Load passenger data
passenger_demand_df = pd.read_csv(os.path.join(OUTPUT_DATA_DIR_PATH, "deminit_trde_per_capita_passenger_km.csv"))
passenger_demand_df.head()

,year,deminit_trde_private_and_public_per_capita_passenger_km,deminit_trde_regional_per_capita_passenger_km
0,2015,2245.495980,43.393178
1,2016,2352.897913,45.468671
2,2017,2426.772259,46.896259
3,2018,2579.635329,49.850267
4,2019,2745.852607,53.062340

In [6]:
# human_powered``|``powered_bikes``|``public``|``road_light``|``water_borne
private_and_public_mode_shares = {
    "human_powered": 0.0,
    "powered_bikes": 0.5546,
    "public": 0.1260,
    "road_light": 0.3193,
    "water_borne": 0.0
}


# aviation``|``rail_passenger``|``road_heavy_regional``|``road_light``|``water_borne
regional_mode_shares = {
    "aviation": 0.9918,
    "rail_passenger": 0.0002,
    "road_heavy_regional": 0.0,
    "road_light": 0.0,
    "water_borne": 0.0080
}

# aviation``|``rail_freight``|``road_heavy_freight``|``water_borne
freight_mode_shares = {
    "aviation": 0.0020,
    "rail_freight": 0.0015,
    "road_heavy_freight": 0.8698,
    "water_borne": 0.1267
}

In [7]:
passenger_mode_share_df = passenger_demand_df.copy()

In [8]:
for key, value in private_and_public_mode_shares.items():
    var_name = f"frac_trns_pkm_dem_private_and_public_{key}"
    passenger_mode_share_df[var_name] =  passenger_demand_df["deminit_trde_private_and_public_per_capita_passenger_km"] * value

for key, value in regional_mode_shares.items():
    var_name = f"frac_trns_pkm_dem_regional_{key}"
    passenger_mode_share_df[var_name] =  passenger_demand_df["deminit_trde_regional_per_capita_passenger_km"] * value

In [9]:
passenger_mode_share_df.head()

,year,deminit_trde_private_and_public_per_capita_passenger_km,deminit_trde_regional_per_capita_passenger_km,frac_trns_pkm_dem_private_and_public_human_powered,frac_trns_pkm_dem_private_and_public_powered_bikes,frac_trns_pkm_dem_private_and_public_public,frac_trns_pkm_dem_private_and_public_road_light,frac_trns_pkm_dem_private_and_public_water_borne,frac_trns_pkm_dem_regional_aviation,frac_trns_pkm_dem_regional_rail_passenger,frac_trns_pkm_dem_regional_road_heavy_regional,frac_trns_pkm_dem_regional_road_light,frac_trns_pkm_dem_regional_water_borne
0,2015,2245.495980,43.393178,0.0,1245.352070,282.932493,716.986866,0.0,43.037354,0.008679,0.0,0.0,0.347145
1,2016,2352.897913,45.468671,0.0,1304.917183,296.465137,751.280304,0.0,45.095828,0.009094,0.0,0.0,0.363749
2,2017,2426.772259,46.896259,0.0,1345.887895,305.773305,774.868382,0.0,46.511709,0.009379,0.0,0.0,0.375170
3,2018,2579.635329,49.850267,0.0,1430.665753,325.034051,823.677560,0.0,49.441495,0.009970,0.0,0.0,0.398802
4,2019,2745.852607,53.062340,0.0,1522.849856,345.977428,876.750737,0.0,52.627229,0.010612,0.0,0.0,0.424499

In [10]:
passenger_mode_share_df.drop(columns=["deminit_trde_private_and_public_per_capita_passenger_km",
                                      "deminit_trde_regional_per_capita_passenger_km"], inplace=True)
passenger_mode_share_df.head()

,year,frac_trns_pkm_dem_private_and_public_human_powered,frac_trns_pkm_dem_private_and_public_powered_bikes,frac_trns_pkm_dem_private_and_public_public,frac_trns_pkm_dem_private_and_public_road_light,frac_trns_pkm_dem_private_and_public_water_borne,frac_trns_pkm_dem_regional_aviation,frac_trns_pkm_dem_regional_rail_passenger,frac_trns_pkm_dem_regional_road_heavy_regional,frac_trns_pkm_dem_regional_road_light,frac_trns_pkm_dem_regional_water_borne
0,2015,0.0,1245.352070,282.932493,716.986866,0.0,43.037354,0.008679,0.0,0.0,0.347145
1,2016,0.0,1304.917183,296.465137,751.280304,0.0,45.095828,0.009094,0.0,0.0,0.363749
2,2017,0.0,1345.887895,305.773305,774.868382,0.0,46.511709,0.009379,0.0,0.0,0.375170
3,2018,0.0,1430.665753,325.034051,823.677560,0.0,49.441495,0.009970,0.0,0.0,0.398802
4,2019,0.0,1522.849856,345.977428,876.750737,0.0,52.627229,0.010612,0.0,0.0,0.424499

In [12]:
passenger_mode_share_df.tail()

,year,frac_trns_pkm_dem_private_and_public_human_powered,frac_trns_pkm_dem_private_and_public_powered_bikes,frac_trns_pkm_dem_private_and_public_public,frac_trns_pkm_dem_private_and_public_road_light,frac_trns_pkm_dem_private_and_public_water_borne,frac_trns_pkm_dem_regional_aviation,frac_trns_pkm_dem_regional_rail_passenger,frac_trns_pkm_dem_regional_road_heavy_regional,frac_trns_pkm_dem_regional_road_light,frac_trns_pkm_dem_regional_water_borne
82,2096,0.0,1522.849856,345.977428,876.750737,0.0,52.627229,0.010612,0.0,0.0,0.424499
83,2097,0.0,1522.849856,345.977428,876.750737,0.0,52.627229,0.010612,0.0,0.0,0.424499
84,2098,0.0,1522.849856,345.977428,876.750737,0.0,52.627229,0.010612,0.0,0.0,0.424499
85,2099,0.0,1522.849856,345.977428,876.750737,0.0,52.627229,0.010612,0.0,0.0,0.424499
86,2100,0.0,1522.849856,345.977428,876.750737,0.0,52.627229,0.010612,0.0,0.0,0.424499

In [11]:
passenger_mode_share_df.to_csv(os.path.join(OUTPUT_DATA_DIR_PATH, "frac_trns_pkm_dem.csv"), index=False)